all: son.bak.txt
	@echo I am all # display I am all on screen
	
son.bak.txt: son.txt
	@echo I am son.bak.txt # display I am son.bak.txt on screen
	@cp son.txt son.bak.txt # copy son.txt to son.bak.txt

clean:
	@rm son.bak.txt