all: son mom dad grandma grandpa
	@echo "finish        @" "$(shell date)"

son: 
	@echo "son     begin @" "$(shell date)"
	@sleep 2
	@echo "son     end"

mom: 
	@echo "mom     begin @" "$(shell date)"
	@sleep 3
	@echo "mom     end"

dad: 
	@echo "dad     begin @" "$(shell date)"
	@sleep 5
	@echo "dad     end"

grandma:
	@echo "grandma begin @" "$(shell date)"
	@sleep 3
	@echo "grandma end"

grandpa:
	@echo "grandpa begin @" "$(shell date)"
	@sleep 5
	@echo "grandpa end"